# GitHub Actions CI/CD — ECR + SSM + EC2

name: Flask App CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: flask-student-app

jobs:

  # ============================================================
  # 1. Run tests
  # ============================================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: |
          python -m pytest 


  # ============================================================
  # 2. Build Docker image and push to ECR
  # ============================================================
  build-and-push:
    name: Build and Push to ECR
    needs: test
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check GitHub environment
        run: |
            echo "Repository: ${{ github.repository }}"
            echo "Ref: ${{ github.ref }}"
            echo "Event: ${{ github.event_name }}" 
      - name: Check OIDC permissions
        run: |
            echo "ACTIONS_ID_TOKEN_REQUEST_URL is set:"
            if [ -n "$ACTIONS_ID_TOKEN_REQUEST_URL" ]; then
                echo "YES"
            else
                echo "NO"
            fi

            echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN is set:"
            if [ -n "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]; then
                echo "YES"
            else
                echo "NO"
            fi
      - name: Check OIDC token claims
        env:
            ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
            ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        run: |
            TOKEN=$(curl -sS \
                -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
                | python -c "import sys,json; print(json.load(sys.stdin)['value'])")

            echo "OIDC token received successfully"

            python - "$TOKEN" <<'PY'
            import sys
            import base64
            import json

            token = sys.argv[1]
            payload = token.split(".")[1]
            payload += "=" * (-len(payload) % 4)

            claims = json.loads(base64.urlsafe_b64decode(payload))

            print("iss:", claims.get("iss"))
            print("aud:", claims.get("aud"))
            print("sub:", claims.get("sub"))
            print("repository:", claims.get("repository"))
            print("ref:", claims.get("ref"))
            print("exp:", claims.get("exp"))
            print("iat:", claims.get("iat"))
            PY
      

          # 🆕 NEW
      - name: Set Docker image tag from Git commit SHA
        id: image-tag
        run: |
          IMAGE_TAG="${GITHUB_SHA}"
          echo "IMAGE_TAG=${IMAGE_TAG}"
          echo "image_tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"


            
      # --------------------------------------------------------
      # Configure AWS using GitHub OIDC
      # --------------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490600801130:role/GitHubActions-Flask-ECR-Role
          aws-region: ${{ env.AWS_REGION }}

      # --------------------------------------------------------
      # Login to Amazon ECR
      # --------------------------------------------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --------------------------------------------------------
      # Build Docker image
      # --------------------------------------------------------
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      # --------------------------------------------------------
      # Push Docker image to ECR
      # --------------------------------------------------------
      - name: Push Docker image to ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}


  # ============================================================
  # 3. Deploy image to EC2 using SSM
  # ============================================================
  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4
    #   - name: Check GitHub environment
    #     run: |
    #         echo "Repository: ${{ github.repository }}"
    #         echo "Ref: ${{ github.ref }}"
    #         echo "Event: ${{ github.event_name }}" 
    # #   # --------------------------------------------------------
      # Configure AWS using GitHub OIDC
      # --------------------------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::490600801130:role/GitHubActions-Flask-ECR-Role
          aws-region: ${{ env.AWS_REGION }}

      # --------------------------------------------------------
      # Deploy to EC2 using SSM
      # --------------------------------------------------------
      - name: Deploy application to EC2
        run: |

          aws ssm send-command \
            --instance-ids "i-0587a697defb611af" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "set -e",

              "echo Logging in to ECR...",

              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 490600801130.dkr.ecr.us-east-1.amazonaws.com",

              "echo Pulling latest image...",

              "docker pull 490600801130.dkr.ecr.us-east-1.amazonaws.com/flask-student-app:${{ github.sha }}",

              "echo Stopping old container...",

              "docker stop flask-student-app || true",

              "echo Removing old container...",

              "docker rm flask-student-app || true",

              "echo Starting new container...",

              "docker run -d --name flask-student-app --restart unless-stopped -p 5000:5000 --env-file /home/ec2-user/.env 490600801130.dkr.ecr.us-east-1.amazonaws.com/flask-student-app:${{ github.sha }}",

              "echo Deployment completed successfully.",

              "docker ps"
            ]'





   # ==========================================================
  # JOB 5 - SUCCESS EMAIL
  # ==========================================================

  notify-success:

    name: Send Deployment Success Email

    needs: deploy

    if: ${{ needs.deploy.result == 'success' }}

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # Send email
      # ------------------------------------------------------

      - name: Send success email
        uses: dawidd6/action-send-mail@v6

        with:

          server_address: ${{ secrets.SMTP_SERVER }}

          server_port: ${{ secrets.SMTP_PORT }}

          username: ${{ secrets.SMTP_USERNAME }}

          password: ${{ secrets.SMTP_PASSWORD }}


          # --------------------------------------------------
          # Email subject
          # --------------------------------------------------

          subject: "SUCCESS - Flask Application Deployed"


          # --------------------------------------------------
          # Recipient
          # --------------------------------------------------

          to: ${{ secrets.NOTIFICATION_EMAIL }}

          from: ${{ secrets.SMTP_USERNAME }}


          # --------------------------------------------------
          # Email body
          # --------------------------------------------------

          content_type: text

          body: |

            ==================================================
            FLASK APPLICATION DEPLOYMENT SUCCESSFUL
            ==================================================


            STATUS
            --------------------------------------------------
            SUCCESS


            GIT INFORMATION
            --------------------------------------------------

            Repository:
            ${{ github.repository }}

            Branch:
            ${{ github.ref_name }}

            Commit SHA:
            ${{ github.sha }}


            DOCKER / ECR INFORMATION
            --------------------------------------------------

            ECR Repository:
            ${{ env.ECR_REPOSITORY }}

            Docker Image Tag:
            ${{ env.IMAGE_TAG }}

            Full Docker Image:
            490600801130.dkr.ecr.us-east-1.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}


            EC2 DEPLOYMENT
            --------------------------------------------------

            EC2 Instance:
            ${{ secrets.INSTANCE_ID }}

            Container:
            ${{ env.CONTAINER_NAME }}


            GITHUB ACTIONS PIPELINE
            --------------------------------------------------

            Workflow:
            ${{ github.workflow }}

            Run Number:
            ${{ github.run_number }}

            Pipeline Run:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}


            ==================================================
            Deployment completed successfully.
    # ==========================================================     


  # ==========================================================
  # JOB 6 - FAILURE EMAIL
  # ==========================================================

  notify-failure:

    name: Send Deployment Failure Email

    needs:
      - test
      - build-and-push
      - deploy

    # Run this job even if one of the previous jobs failed
    if: ${{ always() && (needs.test.result == 'failure' || needs.build.result == 'failure' || needs.push.result == 'failure' || needs.deploy.result == 'failure') }}

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------------------
      # Identify which stage failed
      # ------------------------------------------------------

      - name: Identify failed stage
        id: failure_stage
        shell: bash
        run: |

          if [ "${{ needs.test.result }}" = "failure" ]; then
            echo "stage=TEST" >> "$GITHUB_OUTPUT"

          elif [ "${{ needs.build-and-push.result }}" = "failure" ]; then
            echo "stage=BUILD" >> "$GITHUB_OUTPUT"

         
          elif [ "${{ needs.deploy.result }}" = "failure" ]; then
            echo "stage=DEPLOYMENT" >> "$GITHUB_OUTPUT"

          else
            echo "stage=UNKNOWN" >> "$GITHUB_OUTPUT"
          fi


      # ------------------------------------------------------
      # Send failure email
      # ------------------------------------------------------

      - name: Send failure email
        uses: dawidd6/action-send-mail@v6

        with:

          server_address: ${{ secrets.SMTP_SERVER }}

          server_port: ${{ secrets.SMTP_PORT }}

          username: ${{ secrets.SMTP_USERNAME }}

          password: ${{ secrets.SMTP_PASSWORD }}

          # --------------------------------------------------
          # Failure subject
          # --------------------------------------------------

          subject: "FAILED - Flask Deployment - ${{ steps.failure_stage.outputs.stage }}"

          # --------------------------------------------------
          # Recipient
          # --------------------------------------------------

          to: ${{ secrets.NOTIFICATION_EMAIL }}

          from: ${{ secrets.SMTP_USERNAME }}

          # --------------------------------------------------
          # Email body
          # --------------------------------------------------

          content_type: text

          body: |

            ==================================================
            FLASK APPLICATION DEPLOYMENT FAILED
            ==================================================

            STATUS
            --------------------------------------------------
            ❌ FAILED


            FAILED STAGE
            --------------------------------------------------
            ${{ steps.failure_stage.outputs.stage }}


            GIT INFORMATION
            --------------------------------------------------

            Repository:
            ${{ github.repository }}

            Branch:
            ${{ github.ref_name }}

            Commit SHA:
            ${{ github.sha }}


            PIPELINE INFORMATION
            --------------------------------------------------

            Workflow:
            ${{ github.workflow }}

            Run Number:
            ${{ github.run_number }}

            Run ID:
            ${{ github.run_id }}


            STAGE RESULTS
            --------------------------------------------------

            TEST:
            ${{ needs.test.result }}

            BUILD:
            ${{ needs.build.result }}

            PUSH TO ECR:
            ${{ needs.push.result }}

            DEPLOY:
            ${{ needs.deploy.result }}


            INVESTIGATE FAILURE
            --------------------------------------------------

            Open the GitHub Actions run here:

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}


            Commit:
            https://github.com/${{ github.repository }}/commit/${{ github.sha }}


            ==================================================
            Deployment failed.

            Please check the failed stage and GitHub Actions
            logs using the links above.


            


            